language: node_js
node_js:
  - "4.1.0"
before_script:
  - npm install -g mocha

services:
  - docker

before_install:

  - echo "{$DOCKER_PASSWORD}" | docker login -u "$DOCKER_USERNAME" --password-stdin https://us.gcr.io
  - docker push us.gcr.io/sre-cedille/canoe-beton:$TAG

script:
  - bundle exec rake test
