language: node_js
node_js:
- 4.1.0
before_script:
- npm install -g mocha
notifications:
  email: false
cache:
  directories:
  - "$HOME/google-cloud-sdk"
services:
- docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_7230627466ee_key -iv $encrypted_7230627466ee_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk";
  curl https://sdk.cloud.google.com | bash > /dev/null; fi
- source $HOME/google-cloud-sdk/path.bash.inct
- gcloud components update kubectl

jobs:
  include:
    - stage: build 
      script: cat  /home/travis/build/jalilbengoufa/canoe-beton/secrets/service.json | docker login -u _json_key --password-stdin https://us.gcr.io  && docker build -t us.gcr.io/sre-cedille/canoe-beton:latest .
    - stage: "push"
      script: docker push us.gcr.io/sre-cedille/canoe-beton:latest
    - stage: deploy
      script: kubectl set image deployment canoe -n canoe canoe=us.gcr.io/sre-cedille/canoe-beton:latest --kubeconfig /home/travis/build/jalilbengoufa/canoe-beton/secrets/configt && kubectl set image deployment canoe -n canoe canoe=us.gcr.io/sre-cedille/canoe-beton --kubeconfig /home/travis/build/jalilbengoufa/canoe-beton/secrets/configt

install: true
script: true
