language: node_js
node_js:
  - "4.1.0"
before_script:
  - npm install -g mocha

notifications:
  email: false

cache:
  directories:
  # We cache the SDK so we don't have to download it again on subsequent builds.
  - $HOME/google-cloud-sdk
services:
# Include the docker service so you can roll your own images.
# You can remove this if you already have images somewhere else.
- docker
env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1 
before_install:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash > /dev/null; fi
# This line is critical. We setup the SDK to take precedence in our
# environment over the old SDK that is already on the machine.
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud version
- echo $KUBETEST >> /home/travis/config
- export KUBECONFIG=/home/travis/config  && cat /home/travis/config 
- cd /home && ls -a
- kubectl set image deployment canoe -n canoe canoe=us.gcr.io/sre-cedille/canoe-beton:latest
# Insert your own install + script below.
install: true
script: true